### ISSUE TITLE
Update evm2wasm

### ISSUE THREAD

**Issue by lrettig** [ewasm/pm#17]
- [ ] Add Byzantium support to evm2wasm (ewasm/evm2wasm#163)
- [ ] Update gas costs to Byzantium in evm2wasm (ewasm/evm2wasm#164)
- [ ] Support new call/create EEI methods (ewasm/evm2wasm#184)

**Comment by axic** [comment]
I think this is better managed as a Github project on evm2wasm.
